name: Publish Artifact

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Setup npm script
        run: npm i
      - name: Build for linux
        run: npm run build-lin
      - name: Remove build files Nr. 1
        run: rm -rf dist/*-unpacked
      - name: Remove build files Nr. 2
        run: rm -rf dist/*.yml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build_lin
          path: dist/*

  build-win:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Setup npm script
        run: npm i
      - name: Build for windows
        run: npm run build-win
      - name: Remove build files Nr. 1
        run: Remove-Item -Recurse -Force dist/*-unpacked
      - name: Remove build files Nr. 2
        run: Remove-Item -Force dist/*.yml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build_win
          path: dist/*

  build-mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Setup npm script
        run: npm i
      - name: Build for Macos
        run: npm run build-mac
      - name: Remove build files Nr. 1
        run: rm -rf dist/*-unpacked
      - name: Remove build files Nr. 2
        run: rm -rf dist/*.yml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build_mac
          path: dist/*
