name: Publish Artifact

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          branch: dev
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Setup npm script
        run: npm i
      - name: Build for linux
        run: npm run build-lin
      - name: Remove build files Nr. 1
        run: rm -rf dist/*-unpacked
      - name: Remove build files Nr. 2
        run: rm -rf dist/*.yml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build_lin
          path: dist/*

  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Setup npm script
        run: npm i
      - name: Build for windows
        run: npm run build-win
      - name: Remove build files Nr. 1
        run: deltree /S /Q dist/*-unpacked
      - name: Remove build files Nr. 2
        run: del /Q dist/*.yml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build_win
          path: dist/*

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Setup npm script
        run: npm i
      - name: Build for Macos
        run: npm run build-mac
      - name: Remove build files Nr. 1
        run: rm -rf dist/*-unpacked
      - name: Remove build files Nr. 2
        run: rm -rf dist/*.yml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build_mac
          path: dist/*
